name: Build and Test @sb-mig monorepo packages

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Building deps
        run: yarn

      - name: Building packages
        run: yarn start

      - name: Linking packages
        run: npx lerna link

      - name: Prepare repository
        run: git reset --hard HEAD
