name: Build and Publish @sb-mig monorepo packages

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Building deps
        run: yarn

      - name: Building packages
        run: yarn start

      - name: Linking packages
        run: npx lerna link

      - name: Prepare repository
        run: git reset --hard HEAD

      - name: Publishing on npm registry
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NO_HUSKY: 1
        run: |
          git config --global user.name 'Marcin Krawczyk'
          git config --global user.email 'marckraw@icloud.com'
          git log -n 1
          git status
          npx lerna publish --conventional-commits --changelog-preset conventionalcommits -m 'chore(release): publish' --yes
